import { Mandal, CuratedRoute } from "./types";

export const MANDALS: Mandal[] = [
  // MANACHE PAACH (5 — ceremonial order matters)
  {
    id: "kasba-ganpati",
    name: "Shri Kasba Ganpati",
    nameMarathi: "श्री कसबा गणपती",
    lat: 18.5167,
    lng: 73.8553,
    area: "Kasba Peth",
    categories: ["manache"],
    established: 1893,
    verified: true,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Kasba%20Ganpati%20Temple%2C%20Pune.jpg",
    description: "The first among the Manache Paach — Pune's own Gramdaivat Ganpati, established in 1893.",
    tips: "Traditional wooden sanctum with a quiet morning darshan queue. Walkable from Shaniwar Wada.",
  },
  {
    id: "tambdi-jogeshwari",
    name: "Tambdi Jogeshwari Ganpati",
    nameMarathi: "तांबडी जोगेश्वरी गणपती",
    lat: 18.5142,
    lng: 73.8562,
    area: "Budhwar Peth",
    categories: ["manache"],
    established: 1893,
    verified: true,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Tambdi%20Jogeshwari%20Temple.jpg",
    description: "The second Manacha Ganpati in Pune, honoring the patron deity of the city.",
    tips: "Located in the heart of Budhwar Peth. Morning walk from Kasba Ganpati takes under 5 minutes.",
  },
  {
    id: "guruji-talim",
    name: "Guruji Talim Ganpati",
    nameMarathi: "गुरुजी तालीम गणपती",
    lat: 18.5136,
    lng: 73.8558,
    area: "Budhwar Peth",
    categories: ["manache"],
    established: 1887,
    verified: true,
    imageUrl: "/images/mandals/guruji-talim.jpg",
    description: "The third Manacha Ganpati, established by Hindu and Muslim wrestlers together in 1887.",
    tips: "Located right on Laxmi Road. Features grand thematic decorations and vibrant lighting.",
  },
  {
    id: "tulshibaug-ganpati",
    name: "Tulshibaug Ganpati",
    nameMarathi: "तुळशीबाग गणपती",
    lat: 18.5128,
    lng: 73.8564,
    area: "Budhwar Peth",
    categories: ["manache"],
    established: 1901,
    verified: true,
    imageUrl: "/images/mandals/tulshibaug-ganpati.jpg",
    description: "The fourth Manacha Ganpati, famous for its grand 13-foot idol in Tulshibaug market.",
    tips: "Surrounded by market lanes. Foot traffic is busiest during late afternoon and evening.",
  },
  {
    id: "kesariwada-ganpati",
    name: "Kesariwada Ganpati",
    nameMarathi: "केसरीवाडा गणपती",
    lat: 18.5148,
    lng: 73.8530,
    area: "Narayan Peth",
    categories: ["manache"],
    established: 1894,
    verified: true,
    imageUrl: "/images/mandals/kesariwada-ganpati.jpg",
    description: "The fifth Manacha Ganpati, founded by Lokmanya Bal Gangadhar Tilak at Kesariwada.",
    tips: "Visit the Tilak museum located in the same courtyard. Peaceful ambiance compared to market routes.",
  },

  // FAMOUS MANDALS
  {
    id: "dagdusheth-halwai-ganpati",
    name: "Shrimant Dagdusheth Halwai Ganpati",
    nameMarathi: "श्रीमंत दगडूशेठ हलवाई गणपती",
    lat: 18.5162,
    lng: 73.8554,
    area: "Budhwar Peth",
    categories: ["famous"],
    established: 1893,
    googlePlaceId: "ChIJtUMvBFLBwjsRobTYBPMYKh8",
    verified: true,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Dagaduseth%20halwai%20ganpati.jpg",
    description: "Pune's best-known Ganpati. Expect the longest queue of any mandal.",
    tips: "Early morning (before 7am) is materially faster.",
  },
  {
    id: "sarasbaug-ganpati",
    name: "Shri Siddhivinayak, Sarasbaug",
    nameMarathi: "श्री सिद्धिविनायक, सारसबाग",
    lat: 18.5019,
    lng: 73.8554,
    area: "Sadashiv Peth",
    categories: ["famous", "temple"],
    established: 1784,
    verified: true,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Sarasbaug%2CPune.jpg",
    description: "A year-round temple, not a festival pandal.",
    tips: "Spacious green garden with easy parking and sunset illumination.",
  },
  {
    id: "akhil-mandai-mandal",
    name: "Akhil Mandai Mandal",
    nameMarathi: "अखिल मंडई मंडळ",
    lat: 18.5152,
    lng: 73.8578,
    area: "Shukrawar Peth",
    categories: ["famous"],
    established: 1894,
    verified: true,
    imageUrl: "/images/mandals/akhil-mandai-mandal.jpg",
    description: "Distinguished by its unique idol showing Lord Ganesha seated alongside Goddess Sharada, established by market traders at Mahatma Phule Mandai.",
    tips: "Wide open pavilion in front of the historic Mandai clock tower.",
  },
  {
    id: "chhatrapati-rajaram-mandal",
    name: "Chhatrapati Rajaram Mandal",
    nameMarathi: "छत्रपती राजाराम मंडळ",
    lat: 18.5111,
    lng: 73.8520,
    area: "Sadashiv Peth",
    categories: ["famous"],
    established: 1892,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Renowned community mandal in Sadashiv Peth with rich cultural traditions and classical decorations.",
  },
  {
    id: "bhau-rangari-ganpati",
    name: "Shrimant Bhausaheb Rangari Ganpati",
    nameMarathi: "श्रीमंत भाऊसाहेब रंगारी गणपती",
    lat: 18.5158,
    lng: 73.8548,
    area: "Budhwar Peth",
    categories: ["famous", "historic"],
    established: 1892,
    verified: true,
    imageUrl: "/images/mandals/bhau-rangari-ganpati.jpg",
    description: "Pioneered public Ganesh festival in 1892. Features a distinctive wooden chariot and an idol showing Ganesha vanquishing a demon.",
    tips: "Located just behind Dagdusheth. Rich in freedom struggle heritage.",
  },
  {
    id: "shri-morya-gosavi",
    name: "Shri Morya Gosavi Ganpati Mandir",
    nameMarathi: "श्री मोरया गोसावी गणपती मंदिर",
    lat: 18.6298,
    lng: 73.8013,
    area: "Chinchwad",
    categories: ["famous", "temple"],
    established: 1600,
    verified: true,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/%C5%BB%C3%B3%C5%82w2.jpg",
    description: "Ancient riverside temple associated with the Ganapatya saint Morya Gosavi.",
  },
  {
    id: "hatti-ganpati-mandal",
    name: "Hatti Ganpati Mandal",
    nameMarathi: "हत्ती गणपती मंडळ",
    lat: 18.5199,
    lng: 73.8553,
    area: "Kasba Peth",
    categories: ["famous"],
    established: 1893,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Historic mandal featuring majestic elephant statues flanking the altar.",
  },

  // HISTORIC MANDALS
  {
    id: "hutatma-babu-genu-mandal",
    name: "Hutatma Babu Genu Mandal",
    nameMarathi: "हुतात्मा बाबू गेनू मंडळ (नवसाचा गणपती)",
    lat: 18.5143,
    lng: 73.8556,
    area: "Budhwar Peth",
    categories: ["historic"],
    established: 1970,
    verified: true,
    imageUrl: "/images/mandals/hutatma-babu-genu-mandal.jpg",
    imageVerificationStatus: "verified",
    locationAccuracy: "verified",
    locationSource: "GV74+P62 Maarne Heights, 1111, opposite Tilak Statue, Tulshibaug, Budhwar Peth, Pune 411002",
    theme2026: "Somnath Temple",
    themeVerificationStatus: "verified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Named after freedom fighter Babu Genu Said, located in the garment market of Budhwar Peth, famous for wish-fulfilling deity status and the 2026 Somnath Temple replica.",
    researchSource: "Current 2026 Pune Ganpati reporting & official listing",
  },
  {
    id: "shanipar-mandal",
    name: "Shanipar Mandal Trust",
    nameMarathi: "शनिपार मंडळ ट्रस्ट",
    lat: 18.5126,
    lng: 73.8526,
    area: "Sadashiv Peth",
    categories: ["historic"],
    established: 1893,
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "GV73+22V Shashikant Gogvale Path, opposite Shanipar Bus Stop, Perugate, Sadashiv Peth, Pune 411030",
    theme2026: "Shambhala",
    themeVerificationStatus: "verified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Traditional mandal situated at the historic Shanipar Chowk in Sadashiv Peth, presenting the 2026 'Shambhala' theme.",
    researchSource: "Current 2026 Pune Ganpati reporting & location directory",
  },

  // NEIGHBOURHOOD MANDALS (15 to 30)
  {
    id: "kasba-peth-tarun-mandal",
    name: "Kasba Peth Tarun Mandal",
    nameMarathi: "कसबा पेठ तरुण मंडळ",
    lat: 18.5172,
    lng: 73.8551,
    area: "Kasba Peth",
    categories: ["neighbourhood"],
    established: 1952,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Vibrant community mandal in Kasba Peth celebrated for lively dhol tasha beats and traditional tableaus.",
  },
  {
    id: "pawale-chowk-mandal",
    name: "Pawale Chowk Mitra Mandal",
    nameMarathi: "पावळे चौक मित्र मंडळ",
    lat: 18.5178,
    lng: 73.8549,
    area: "Kasba Peth",
    categories: ["neighbourhood"],
    established: 1965,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Popular neighborhood pandal near Shaniwar Wada with elaborate electrical illumination.",
  },
  {
    id: "jilbya-maruti-mandal",
    name: "Jilbya Maruti Ganpati Mandal",
    nameMarathi: "जिलब्या मारुती गणपती मंडळ",
    lat: 18.5141,
    lng: 73.8569,
    area: "Budhwar Peth",
    categories: ["neighbourhood", "historic"],
    established: 1954,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Renowned for intricate floral and artistic stage decorations in Budhwar Peth.",
  },
  {
    id: "sonya-maruti-mandal",
    name: "Sonya Maruti Chowk Mandal",
    nameMarathi: "सोन्या मारुती चौक मंडळ",
    lat: 18.5147,
    lng: 73.8573,
    area: "Budhwar Peth",
    categories: ["neighbourhood"],
    established: 1960,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Situated in the jewelry and trade market of Sonya Maruti Chowk, known for ornate gold jewelry themes.",
  },
  {
    id: "jogeshwari-galli-mandal",
    name: "Jogeshwari Galli Mandal",
    nameMarathi: "जोगेश्वरी गल्ली मित्र मंडळ",
    lat: 18.5139,
    lng: 73.8565,
    area: "Budhwar Peth",
    categories: ["neighbourhood"],
    established: 1975,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Cozy community mandal in the historic Jogeshwari lane of Budhwar Peth.",
  },
  {
    id: "tulshibaug-lane-mandal",
    name: "Shukrawar Peth Tulshi Lane Mandal",
    nameMarathi: "शुक्रवार पेठ तुळशी गल्ली मंडळ",
    lat: 18.5159,
    lng: 73.8582,
    area: "Shukrawar Peth",
    categories: ["neighbourhood"],
    established: 1980,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Active youth organization in Shukrawar Peth hosting social awareness and cultural programs.",
  },
  {
    id: "badami-haud-mandal",
    name: "Badami Haud Chowk Mandal",
    nameMarathi: "बदामी हौद चौक मंडळ",
    lat: 18.5164,
    lng: 73.8579,
    area: "Shukrawar Peth",
    categories: ["neighbourhood"],
    established: 1968,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Historic water tank chowk mandal known for festive dhol processions.",
  },
  {
    id: "natu-baug-mandal",
    name: "Natu Baug Mandal",
    nameMarathi: "नातू बाग गणपती मंडळ",
    lat: 18.5114,
    lng: 73.8518,
    area: "Sadashiv Peth",
    categories: ["neighbourhood"],
    established: 1980,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Famous for spectacular electrical lighting arches spanning across Sadashiv Peth.",
  },
  {
    id: "perugate-mandal",
    name: "Perugate Mitra Mandal",
    nameMarathi: "पेरूगेट मित्र मंडळ",
    lat: 18.5106,
    lng: 73.8526,
    area: "Sadashiv Peth",
    categories: ["neighbourhood"],
    established: 1962,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Traditional residential pandal in Sadashiv Peth with devotional aartis.",
  },
  {
    id: "modi-ganpati-mandal",
    name: "Modi Ganpati Mandal",
    nameMarathi: "मोदी गणपती मंडळ",
    lat: 18.5139,
    lng: 73.8521,
    area: "Narayan Peth",
    categories: ["neighbourhood"],
    established: 1948,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Historic shrine founded by the Peshwa administration in Narayan Peth.",
  },
  {
    id: "zanjale-chowk-mandal",
    name: "Zanjale Chowk Seva Mandal",
    nameMarathi: "झांजले चौक सेवा मंडळ",
    lat: 18.5145,
    lng: 73.8519,
    area: "Narayan Peth",
    categories: ["neighbourhood"],
    established: 1974,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Community welfare mandal organizing free medical camps and prasad distribution.",
  },
  {
    id: "ganesh-peth-dudh-bhatti",
    name: "Dudh Bhatti Mandal",
    nameMarathi: "दूध भट्टी गणेश मंडळ",
    lat: 18.5092,
    lng: 73.8612,
    area: "Ganesh Peth",
    categories: ["neighbourhood"],
    established: 1955,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Established by the milk traders of Ganesh Peth, famous for ornate dairy market tableaus.",
  },
  {
    id: "dulya-maruti-ganpati",
    name: "Dulya Maruti Chowk Mandal",
    nameMarathi: "डुल्या मारुती चौक गणपती",
    lat: 18.5088,
    lng: 73.8608,
    area: "Ganesh Peth",
    categories: ["neighbourhood"],
    established: 1963,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Located near the sacred Dulya Maruti temple in Ganesh Peth.",
  },
  {
    id: "shaniwar-wada-mandal",
    name: "Shaniwar Wada Prathisthan",
    nameMarathi: "शनिवार वाडा प्रतिष्ठान",
    lat: 18.5198,
    lng: 73.8579,
    area: "Shaniwar Peth",
    categories: ["neighbourhood"],
    established: 1985,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Pandal erected right opposite the historic Delhi Gate of Shaniwar Wada fort.",
  },
  {
    id: "bohra-masjid-ganpati",
    name: "Raviwar Peth Vyapari Mandal",
    nameMarathi: "रविवार पेठ व्यापारी मंडळ",
    lat: 18.5170,
    lng: 73.8590,
    area: "Raviwar Peth",
    categories: ["neighbourhood"],
    established: 1972,
    verified: true,
    imageUrl: "/images/mandals/pune-pandal-default.jpg",
    description: "Trade association mandal in the vibrant wholesale markets of Raviwar Peth.",
  },
  {
    id: "trishund-ganpati-temple",
    name: "Trishund Mayureshwar Ganpati",
    nameMarathi: "त्रिशुंड मयुरेश्वर गणपती",
    lat: 18.5208,
    lng: 73.8622,
    area: "Somwar Peth",
    categories: ["historic", "temple"],
    established: 1770,
    verified: true,
    imageUrl: "/images/mandals/sarasbaug-ganpati.jpg",
    description: "Rare 18th-century stone temple with a 3-trunked Ganpati riding a peacock with exquisite stone carvings.",
  },

  // NEW MANDALS (2026 Expansion & Unique Decorations)
  {
    id: "hamraj-mitra-mandal",
    name: "Hamraj Mitra Mandal",
    nameMarathi: "हमराज मित्र मंडळ",
    lat: 18.5065,
    lng: 73.8052,
    area: "Kothrud",
    categories: ["neighbourhood"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "No. 82/83, Guruganesh Nagar / Shastri Nagar Road, Kothrud, Pune 411038",
    theme2026: null,
    themeClaimedByUser: "Shree Venkateshwar Swami Temple",
    themeVerificationStatus: "unverified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Popular Kothrud mandal on Shastri Nagar Road, known for grand thematic temple decorations during Ganeshotsav.",
    researchSource: "Pune Ganeshotsav directory & community reporting",
  },
  {
    id: "shree-krishna-mandal",
    name: "Shree Krishna Mandal Trust",
    nameMarathi: "श्री कृष्ण मंडळ ट्रस्ट",
    lat: 18.5142,
    lng: 73.8432,
    area: "Deccan Gymkhana",
    categories: ["neighbourhood"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "Khandoji Baba Chowk No. 4, Khilarewadi, Deccan Gymkhana, Pune 411004",
    theme2026: "Candyland",
    themeClaimedByUser: "Candyland (Chocolate Cha Bangla)",
    themeVerificationStatus: "verified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Vibrant Deccan mandal at Khilarewadi, popular for the 2026 'Candyland - Chocolate Cha Bangla' theme.",
    researchSource: "Current 2026 Pune Ganpati reporting",
  },
  {
    id: "shree-sai-mitra-mandal",
    name: "Shree Sai Mitra Mandal",
    nameMarathi: "श्री साई मित्र मंडळ",
    lat: null,
    lng: null,
    area: "Kothrud",
    categories: ["neighbourhood"],
    verified: false,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "unverified",
    locationSource: "Gujrat Colony, Kothrud, Pune 411038",
    theme2026: null,
    themeClaimedByUser: "Kashi Vishwanath Mandir",
    themeVerificationStatus: "unverified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Community mandal based in Gujrat Colony, Kothrud. Known for community celebrations.",
    researchSource: "Kothrud community records",
  },
  {
    id: "shree-gajanan-mitra-mandal",
    name: "Shree Gajanan Mitra Mandal",
    nameMarathi: "श्री गजानन मित्र मंडळ",
    lat: 18.5132,
    lng: 73.8561,
    area: "Budhwar Peth",
    categories: ["neighbourhood"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "Tulshibaug Internal Road, Budhwar Peth, Pune 411002",
    theme2026: "Girikandhar",
    themeClaimedByUser: "Girikandhar (40-foot Hanuman feature)",
    themeVerificationStatus: "verified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Central Pune mandal in Tulshibaug known for grand scenic creations, featuring the 2026 'Girikandhar' concept with 40-foot Hanuman feature.",
    researchSource: "Current 2026 Pune Ganpati reporting",
  },
  {
    id: "samasth-gaavkari-mandal",
    name: "Samasth Gaavkari Mandal",
    nameMarathi: "समस्त गावकरी मंडळ",
    lat: null,
    lng: null,
    area: "Kothrud",
    categories: ["neighbourhood"],
    verified: false,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "unverified",
    locationSource: "Kothrud, Pune",
    theme2026: null,
    themeClaimedByUser: "Mahakaleshwar Jyotirling",
    themeVerificationStatus: "unverified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Historical community mandal representing the traditional village community in Kothrud.",
    researchSource: "Community archive references",
  },
  {
    id: "navjawan-mitra-mandal",
    name: "Navjawan Mitra Mandal",
    nameMarathi: "नौजवान मित्र मंडळ",
    lat: 18.5127,
    lng: 73.8487,
    area: "Sadashiv Peth",
    categories: ["neighbourhood"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "GR7X+3FF, Sadashiv Peth, Pune 411030",
    theme2026: null,
    themeClaimedByUser: "Kalbhairav Mandir (live natak & night performance)",
    themeVerificationStatus: "unverified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Active youth mandal in Sadashiv Peth known for cultural presentations and devotional performances.",
    researchSource: "Sadashiv Peth community records & Plus Code GR7X+3FF",
  },
  {
    id: "shivaji-tarun-mandal",
    name: "Shivaji Tarun Mandal",
    nameMarathi: "शिवाजी तरुण मंडळ",
    lat: 18.5085,
    lng: 73.8545,
    area: "Shukrawar Peth",
    categories: ["neighbourhood"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "Gadikhana Chowk, Shukrawar Peth, Pune 411002",
    theme2026: null,
    themeClaimedByUser: "Kantara-inspired live tableau",
    themeVerificationStatus: "unverified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Long-standing youth mandal at Gadikhana Chowk in Shukrawar Peth, famed for dramatic live tableaus (dekhawe).",
    researchSource: "Gadikhana Chowk community and Ganeshotsav records",
  },
  {
    id: "trimurti-mitra-mandal",
    name: "Trimurti Mitra Mandal",
    nameMarathi: "त्रिमूर्ती मित्र मंडळ",
    lat: 18.5121,
    lng: 73.8234,
    area: "Kothrud",
    categories: ["neighbourhood"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "GR6F+R93, Hanuman Nagar, Kothrud, Pune 411038",
    theme2026: null,
    themeClaimedByUser: "Horror theme",
    themeVerificationStatus: "unverified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Prominent neighborhood mandal in Hanuman Nagar, Kothrud, known for innovative youth dekhawe.",
    researchSource: "Kothrud Hanuman Nagar listings & Plus Code GR6F+R93",
  },
  {
    id: "hanuman-mitra-mandal-pratishthan",
    name: "Hanuman Mitra Mandal Pratishthan",
    nameMarathi: "हनुमान मित्र मंडळ प्रतिष्ठान",
    lat: 18.5185,
    lng: 73.8558,
    area: "Kasba Peth",
    categories: ["neighbourhood"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "Kasba Peth, Pune 411011",
    theme2026: "Punawadi / Old Pune",
    themeVerificationStatus: "verified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Traditional Kasba Peth mandal presenting the 2026 'Punawadi / Old Pune' recreation of historical Pune architecture.",
    researchSource: "Current 2026 Pune Ganpati reporting & Kasba Peth records",
  },
  {
    id: "nimbalkar-talim-mandal",
    name: "Nimbalkar Talim Mandal",
    nameMarathi: "निंबाळकर तालीम मंडळ",
    lat: 18.5119,
    lng: 73.8518,
    area: "Sadashiv Peth",
    categories: ["historic", "neighbourhood"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "GV62+QP4 Vasantrao Limaye Road, Perugate, Sadashiv Peth, Pune 411030",
    theme2026: null,
    themeClaimedByUser: "Ramayan (Sita Swayamvar live natak)",
    themeVerificationStatus: "unverified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Traditional wrestling talim mandal on Vasantrao Limaye Road in Perugate, Sadashiv Peth, established in the historic talim culture of Pune.",
    researchSource: "Sadashiv Peth Perugate listings & Plus Code GV62+QP4",
  },
  {
    id: "shri-garud-ganpati-mandal",
    name: "Shri Garud Ganpati Mandal",
    nameMarathi: "श्री गरुड गणपती मंडळ",
    lat: 18.5133,
    lng: 73.8488,
    area: "Narayan Peth",
    categories: ["historic", "temple"],
    verified: true,
    imageUrl: null,
    imageVerificationStatus: "not_verified",
    locationAccuracy: "lane",
    locationSource: "Garud Ganpati Chowk, Laxmi Road / VG Kothari Path, Narayan Peth, Pune 411030",
    theme2026: null,
    themeClaimedByUser: "Adhishakti - 10 avatars of Adhishakti",
    themeVerificationStatus: "unverified",
    category: "unique-decoration",
    tags: ["unique-decoration"],
    description: "Historic shrine at Garud Ganpati Chowk on Laxmi Road, Narayan Peth, venerated for generations.",
    researchSource: "Narayan Peth Laxmi Road listings & Garud Ganpati records",
  },
];

export const CURATED_ROUTES: CuratedRoute[] = [
  {
    id: "manache-paach",
    title: "The Manache Paach Darshan",
    titleMarathi: "मानाचे पाच गणपती परिक्रमा",
    tagline: "Pune's five historic honored Ganpatis in traditional sequence",
    mandalCount: 5,
    approxDistance: "1.8 km",
    approxWalkTime: "35 mins",
    mandalIds: [
      "kasba-ganpati",
      "tambdi-jogeshwari",
      "guruji-talim",
      "tulshibaug-ganpati",
      "kesariwada-ganpati",
    ],
  },
  {
    id: "heart-of-pune",
    title: "Heart of Old Pune Core",
    titleMarathi: "मध्यवर्ती पुणे दर्शन",
    tagline: "Dagdusheth, Mandai, Rangari & Manache highlights in Budhwar Peth",
    mandalCount: 6,
    approxDistance: "2.1 km",
    approxWalkTime: "45 mins",
    mandalIds: [
      "dagdusheth-halwai-ganpati",
      "bhau-rangari-ganpati",
      "tulshibaug-ganpati",
      "akhil-mandai-mandal",
      "jilbya-maruti-mandal",
      "guruji-talim",
    ],
  },
  {
    id: "heritage-trail",
    title: "Freedom & Heritage Trail",
    titleMarathi: "ऐतिहासिक वारसा दर्शन",
    tagline: "Mandals intertwined with Lokmanya Tilak & 1890s freedom movement",
    mandalCount: 4,
    approxDistance: "1.5 km",
    approxWalkTime: "30 mins",
    mandalIds: [
      "kesariwada-ganpati",
      "bhau-rangari-ganpati",
      "kasba-ganpati",
      "guruji-talim",
    ],
  },
];

// Haversine distance in metres between two lat/lng points
export function haversine(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number }
): number {
  const R = 6371000;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const x =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((a.lat * Math.PI) / 180) *
      Math.cos((b.lat * Math.PI) / 180) *
      Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x));
}

// Sort mandals by distance from a point
export function sortByDistance(
  mandals: Mandal[],
  from: { lat: number; lng: number }
): Mandal[] {
  return [...mandals].sort((a, b) => {
    if (a.lat === null || a.lng === null) return 1;
    if (b.lat === null || b.lng === null) return -1;
    return (
      haversine(from, { lat: a.lat, lng: a.lng }) -
      haversine(from, { lat: b.lat, lng: b.lng })
    );
  });
}

// Get nearby mandals for a given mandal (within 500m)
export function getNearby(mandalId: string, radiusM = 500): Mandal[] {
  const source = MANDALS.find((m) => m.id === mandalId);
  if (!source || source.lat === null || source.lng === null) return [];
  return MANDALS
    .filter((m) => m.id !== mandalId && m.lat !== null && m.lng !== null)
    .map((m) => ({
      m,
      dist: haversine(
        { lat: source.lat as number, lng: source.lng as number },
        { lat: m.lat as number, lng: m.lng as number }
      ),
    }))
    .filter(({ dist }) => dist <= radiusM)
    .sort((a, b) => a.dist - b.dist)
    .map(({ m }) => m);
}

export function getMandalById(id: string): Mandal | undefined {
  return MANDALS.find((m) => m.id === id);
}

export function getAllAreas(): string[] {
  const areas = new Set<string>();
  MANDALS.forEach((m) => areas.add(m.area));
  return Array.from(areas);
}
